services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    # Use static, descriptive names for predictability and stability
    image: hse-mlops-homework:latest
    container_name: hse-mlops-app
    working_dir: /app
    volumes:
      # Mount the current directory into the container's /app directory
      - ./:/app
    ports:
      - 8024:8888
    # The command to execute when the container starts
    command: sh -c "python runner.py"
